kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: teiid-operator
subjects:
  - kind: ServiceAccount
    name: teiid-operator
    namespace: placeholder
roleRef:
  kind: ClusterRole
  name: teiid-operator
  apiGroup: rbac.authorization.k8s.io
