apiVersion: apps/v1
kind: Deployment
metadata:
  name: dv-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dv-operator
  template:
    metadata:
      labels:
        name: dv-operator
    spec:
      serviceAccountName: dv-operator
      containers:
      - name: dv-operator
        image: registry.redhat.io/fuse7-tech-preview/dv-rhel7-operator:1.5
        command:
        - teiid-operator
        imagePullPolicy: Always
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace              
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['name']
