kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dv-operator
rules:
  - apiGroups:
      - teiid.io
    resources:
      - "*"
      - "*/finalizers"
    verbs: [ get, list, create, update, delete, deletecollection, watch ]
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - configmaps
      - secrets
      - serviceaccounts
    verbs: [ get, list, create, update, delete, deletecollection, watch ]
  - apiGroups:
      - ""
    resources:
      - replicationcontrollers
      - replicationcontrollers/scale
    verbs: [ get, list, create, update, delete, deletecollection, watch, patch ]
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - deployments/scale
      - replicasets
      - replicasets/scale
      - statefulsets
      - statefulsets/scale
    verbs: [ get, list, create, update, delete, deletecollection, watch, patch ]
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - deployments/scale
      - ingresses
      - networkpolicies
      - replicasets
      - replicasets/scale
      - replicationcontrollers/scale
    verbs: [ get, list, create, update, delete, deletecollection, watch, patch ]
  - apiGroups:
      - ""
    resources:
      - bindings
      - events
      - limitranges
      - namespaces/status
      - pods/log
      - pods/status
      - replicationcontrollers/status
      - resourcequotas
      - resourcequotas/status
    verbs: [ get, list, watch ]
  - apiGroups:
      - ""
      - build.openshift.io
    resources:
      - buildconfigs
      - buildconfigs/webhooks
      - builds
    verbs: [ get, list, create, update, delete, deletecollection, watch, patch ]
  - apiGroups:
      - ""
      - build.openshift.io
    resources:
      - buildconfigs/instantiate
      - buildconfigs/instantiatebinary
      - builds/clone
    verbs: [ create ]
  - apiGroups:
      - ""
      - build.openshift.io
    resources:
      - builds/details
    verbs: [ update ]
  - apiGroups:
      - ""
      - build.openshift.io
    resources:
      - builds/log
    verbs: [ get, list, watch ]
  - apiGroups:
      - ""
      - apps.openshift.io
    resources:
      - deploymentconfigs
      - deploymentconfigs/scale
    verbs: [ get, list, create, update, delete, deletecollection, watch, patch ]
  - apiGroups:
      - ""
      - apps.openshift.io
    resources:
      - deploymentconfigrollbacks
      - deploymentconfigs/instantiate
      - deploymentconfigs/rollback
    verbs: [ create ]
  - apiGroups:
      - ""
      - apps.openshift.io
    resources:
      - deploymentconfigs/log
      - deploymentconfigs/status
    verbs: [ get, list, watch ]
  - apiGroups:
      - ""
      - image.openshift.io
    resources:
      - imagestreams
      - imagestreamimages
      - imagestreammappings
      - imagestreams/secrets
      - imagestreamtags
    verbs: [ get, list, create, update, delete, deletecollection, watch, patch ]
  - apiGroups:
      - ""
      - image.openshift.io
    resources:
      - imagestreamimports
    verbs: [ create ]
  - apiGroups:
      - ""
      - image.openshift.io
    resources:
      - imagestreams/status
    verbs: [ get, list, watch ]
  - apiGroups:
      - ""
    resources:
      - events
    verbs: [ get, list ]
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs: [ get, list, create, update, delete, deletecollection, watch ]
  - apiGroups:
      - ""
      - template.openshift.io
    resources:
      - processedtemplates
      - templateconfigs
      - templateinstances
      - templates
    verbs: [ get, list, create, update, delete, deletecollection, watch, patch ]
  - apiGroups:
      - ""
      - build.openshift.io
    resources:
      - buildlogs
    verbs: [ get, list, create, update, delete, deletecollection, watch, patch ]
  - apiGroups:
      - authorization.openshift.io
    resources:
      - rolebindings
    verbs: [ get, list, create, update, delete, deletecollection, watch ]
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
      - routes/custom-host
    verbs: [ get, list, create, update, delete, deletecollection, watch, patch ]
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - alertmanagers
      - prometheuses
      - servicemonitors
      - prometheusrules
    verbs: [ get, list, create, update, delete, deletecollection, watch]
  - apiGroups:
    - apps
    resourceNames:
    - dv-operator
    resources:
    - deployments/finalizers
    verbs:
    - update    