apiVersion: teiid.io/v1alpha1
kind: VirtualDatabase
metadata:
  name: dv-customer
  annotations:
    consoleName: dv-customer-fatjar
spec:
  replicas: 1
  datasources:
    - name: sampledb
      type: postgresql
      properties:
        - name: username
          value: user
        - name: password
          value: mypassword
        - name: jdbc-url
          value: jdbc:postgresql://sampledb/sampledb
  resources:
    memory: 1024Mi
    cpu: 2.0
  build:
    source:
      maven: org.teiid:dv-customer-fatjar:1.1
